resolver 127.0.0.11 valid=10s ipv6=off;

server {
    listen 8000;
    client_max_body_size 500m;

    location / {
        set $worker_upstream http://wps-worker:8000;
        proxy_pass $worker_upstream;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Connection "";
        proxy_buffering off;
        proxy_request_buffering off;
        proxy_read_timeout 300s;
        proxy_send_timeout 300s;
    }
}
