[General]
languages=zh_CN
AcceptedEULA=true
FirstRun=false
UpdateMode=manual
CloudServiceEnabled=false

[6.0]
common\DefaultLanguage=2052
common\Local\UILanguage=2052
common\PromeWindowCount=40
plugins\kconfigcentersdk\db_path_type=0
plugins\officespace\flogin\alreadyHandleStockNewDeviceInfo=true
wpsoffice\Application%20Settings\BackupSuccess=1
wpsoffice\Application%20Settings\UpdateRecoverCheckTag=true
common\lastwpsofficeact=1767694423122
common\newInstall=true
prome\HardAcc\LastHardAccMode=Raster
browserapp\Application%20Settings\ICCapturedCrash=0
common\AcceptedEULA=true
common\UserInfo\ACUPI=true
common\FileDialog\DefaultRecentLoc\recentLoc_this_PC_pos=0
common\FileDialog\HomepageFavNode\recentLoc_this_PC=1
common\loginSafeVersion=true
plugins\officespace\flogin\enableForceLogin=true
wpsoffice\Application%20Settings\AppComponentMode=prome_independ
wpsoffice\Application%20Settings\AppComponentModeInstall=prome_independ
